#!/usr/bin/env bash
# SubagentStop hook: detects research sessions closing with HIGH confidence
# and writes a cascade suggestion file that the main session can act on.
set -uo pipefail

PAYLOAD=$(cat)
# Extract agent info from payload
AGENT_TYPE=$(echo "$PAYLOAD" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('agent_type',''))" 2>/dev/null || echo "")

# Only fire for research-lead sessions
[[ "$AGENT_TYPE" != *"research"* ]] && exit 0

# Find the most recently modified SYNTHESIS.md in CWD's research teams
CWD=$(echo "$PAYLOAD" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('cwd',''))" 2>/dev/null || echo "$(pwd)")
LATEST_SYNTHESIS=""
LATEST_TIME=0

for f in "$CWD"/.claude/teams/research/*/SYNTHESIS.md; do
  [ -f "$f" ] || continue
  MTIME=$(stat -c%Y "$f" 2>/dev/null || stat -f%m "$f" 2>/dev/null || echo 0)
  if [ "$MTIME" -gt "$LATEST_TIME" ]; then
    LATEST_TIME=$MTIME
    LATEST_SYNTHESIS=$f
  fi
done

[ -z "$LATEST_SYNTHESIS" ] && exit 0

# Check if it has HIGH confidence
if grep -qi "confidence.*high\|HIGH.*confidence\|PASS" "$LATEST_SYNTHESIS" 2>/dev/null; then
  SLUG=$(basename "$(dirname "$LATEST_SYNTHESIS")")

  # Write cascade suggestion
  SUGGESTION_DIR="$CWD/.claude/cascade"
  mkdir -p "$SUGGESTION_DIR"
  cat > "$SUGGESTION_DIR/pending-$SLUG.md" << EOF
# Cascade suggestion: Research → Engineering

Research session \`$SLUG\` closed with HIGH confidence.
SYNTHESIS at: $LATEST_SYNTHESIS

Suggested next dispatch:
\`\`\`
/engineer implement recommendations from research session $SLUG
\`\`\`

Auto-generated by cascade hook at $(date -u +%Y-%m-%dT%H:%M:%SZ).
Delete this file after acting on it or to dismiss.
EOF

  echo "[cascade] wrote suggestion for $SLUG" >&2
fi

exit 0
