#!/usr/bin/env python3
"""Generate docs/CATALOG.md from skill/agent frontmatter.

The catalog is never hand-edited: tests/test_catalog.py regenerates it and
fails CI on drift, so the published inventory cannot lie about the tree.

Usage:
    uv run --group dev python scripts/build_catalog.py          # rewrite docs/CATALOG.md
    uv run --group dev python scripts/build_catalog.py --check  # exit 1 on drift
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "docs" / "CATALOG.md"


def _frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    _, fm, _ = text.split("---", 2)
    return yaml.safe_load(fm)


def _first_sentence(text: str, limit: int = 140) -> str:
    sentence = text.strip().split(". ")[0].rstrip(".")
    if len(sentence) > limit:
        sentence = sentence[: limit - 1].rstrip() + "…"
    return sentence.replace("|", "\\|")


def build_catalog() -> str:
    lines = [
        "# re-forge catalog",
        "",
        "<!-- GENERATED by scripts/build_catalog.py — do not edit by hand.",
        "     tests/test_catalog.py fails CI when this file drifts from the tree. -->",
        "",
    ]

    skills = sorted(REPO_ROOT.glob("skills/*/SKILL.md"))
    lines += [f"## Skills ({len(skills)})", "", "| Skill | Description |", "|---|---|"]
    for path in skills:
        fm = _frontmatter(path)
        rel = path.relative_to(REPO_ROOT).as_posix()
        lines.append(f"| [`{fm['name']}`]({'../' + rel}) | {_first_sentence(fm['description'])} |")
    lines.append("")

    team_dirs = sorted(REPO_ROOT.glob("agents/*-team"))
    for team_dir in team_dirs:
        agents = sorted(p for p in team_dir.glob("*.md") if p.name != "PROTOCOL.md")
        team = team_dir.name.removesuffix("-team")
        lines += [f"## {team.capitalize()} team ({len(agents)} agents)", "", "| Agent | Description |", "|---|---|"]
        for path in agents:
            fm = _frontmatter(path)
            rel = path.relative_to(REPO_ROOT).as_posix()
            lines.append(f"| [`{fm['name']}`]({'../' + rel}) | {_first_sentence(fm['description'])} |")
        lines.append("")

    forge = [REPO_ROOT / "agents" / "forge" / "forge-lead.md"] + sorted(
        REPO_ROOT.glob("agents/forge/skills/*/SKILL.md")
    )
    lines += [f"## Capability Forge ({len(forge)} definitions)", "", "| Definition | Description |", "|---|---|"]
    for path in forge:
        fm = _frontmatter(path)
        rel = path.relative_to(REPO_ROOT).as_posix()
        lines.append(f"| [`{fm['name']}`]({'../' + rel}) | {_first_sentence(fm['description'])} |")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    content = build_catalog()
    if "--check" in sys.argv:
        current = CATALOG_PATH.read_text(encoding="utf-8") if CATALOG_PATH.exists() else ""
        if current != content:
            print("docs/CATALOG.md is stale — run: python scripts/build_catalog.py", file=sys.stderr)
            return 1
        print("docs/CATALOG.md is up to date")
        return 0
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {CATALOG_PATH.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
